---
# tasks file for snmp_exporter
- name: Add Repo
  include_role:
    name: repo
- name: Install Closed Box Exporter
  package:
    name: snmp_exporter
    state: present
  notify: 
    - restart snmp exporter
  become: yes