---
- hosts: all
  become: yes
  tasks:
   - name: installing node expoter
     get_url: 
       url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
       dest: /tmp/
   - name: untar
     unarchive:
       src: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
       dest: /home/vagrant/
       mode: 0755
       remote_src: yes
     register: tar_output
   - debug:
       var: tar_output
   - name: rename
     shell: mv /home/vagrant/node_exporter-1.3.1.linux-amd64 /home/vagrant/node_exporter
   - name: copy the service file
     copy:
       src: /home/vagrant/node_exporter.service
       dest: /home/vagrant/node_exporter.service
       remote_src: no
   - name: copy the service file
     copy:
       src: /home/vagrant/node_exporter.service
       dest: /etc/systemd/system/
       remote_src: no
   - name: service start
     systemd:
       daemon_reload: yes
       state: started
       enabled: yes
       name: node_exporter.service
