---
# handlers file for server
- name: enable prometheus
  service:
    name: prometheus
    daemon_reload: true
    enabled: yes
  become: yes

- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  become: yes

- name: reload prometheus
  service:
    name: prometheus
    state: reloaded
  become: yes