---
# defaults file for server
prometheus_version: "2.24.1"
prometheus_versionlock: yes

prometheus_config_dir: /etc/prometheus

prometheus_web_url: "http://localhost:9090"

prometheus_scrape_interval: 15s
prometheus_evaluation_interval: 15s

prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

prometheus_alert_configs: {}

prometheus_remote_write: []
prometheus_remote_read: []
prometheus_external_labels: {}