---
- name: Install Prometheus Server Package
  ansible.builtin.package:
    name: "prometheus2-{{ prometheus_version }}"
  become: yes
  notify:
    - enable prometheus
    - restart prometheus

- name: Lock Prometheus Version
  community.general.yum_versionlock:
    name: "prometheus2"
    state: present
  when: prometheus_versionlock